name: manage-azure-policy-40d7d1cc
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/Allowed_virtual_machine_size_SKUs_-_Engineering_f9c0a58f-e509-4b3e-af16-45d96b78c2a6/**'
#      - .github/workflows/manage-azure-policy-40d7d1cc.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_40d7d1cc}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/Allowed_virtual_machine_size_SKUs_-_Engineering_f9c0a58f-e509-4b3e-af16-45d96b78c2a6/**
